### ISSUE TITLE
Item transference network deleting items when sorting by 'type'

### ISSUE THREAD

**Issue by 0x0DEDC0DE** [sayterdarkwynd/FrackinUniverse#1403]
https://media.discordapp.net/attachments/447871184953147412/450512440942133278/20180528011514_1.jpg

Relevant, that's how it's wired up (dual stack of shipping containers as source because I had issues actually being able to reach anything past 900 slots/repeater as tested by putting very specific items in)

I set the network to sort by 'type' and started sorting, at first this went well - liquids sorted fine, wire stuff sorted fine, food and seeds sorted fine, decoration, furniture, containers - all sorted fine (implying this is not an issue with the item network's wiring, at least not something directly obvious).

But then I inserted an item of type 'crafting ingredient' into the router, this then fed into a shipping container (300 slots) followed by about 90% of the materials getting poofed out of existence (out of all my materials a couple of stacks of hydrogen, a stack of silicon, and a stack of graphene was all that made it out the other side - all missing items were not present on the storage network).

**Comment by Kherae** [comment]
Points to consider:
First, the item network DOES NOT remove anything unless it can place it. It only removes items after they have been successfully placed. This means your items are not gone.
Second, the network verifies by location, so if objects are put where they aren't supposed to, it is because of a user failing: typically that means you did not confirm that the bridge selected the correct container.
Third: Where's the picture of the ITD's interface? Where is the starbound.log? If you encounter ANY bugs/errors, you need to include a link to pastebin with the FULL log (NO SNIPPETS!)
