### ISSUE TITLE
August 27th update causing server load fault

### ISSUE THREAD

**Issue by samhaintm** [sayterdarkwynd/FrackinUniverse#1533]
Just a quick note on an issue that just popped up. Server is erroring on start with the following exception.
Mod was installed via Steam workshop. Mod and Starbound were uninstalled then reinstalled. Issue persists between installs. Server is starting via PenGUIn. Mod folders have been Symbolically linked and re-linked.

Reported error:
[21:36:54] [Error] Fatal Exception caught: (ObjectException) Error loading object '/objects/bees/honeyextractor/honeyextractor.object': (AssetException) Error loading asset /objects/bees/honeyextractor/honeyextractor.png:default.default

**Comment by sayterdarkwynd** [comment]
Sorry man, but nothing appears amiss with the honey extractor. There were no overly significant changes other than frames file changes and a smaller graphic added. Odd that it fails to load. I'm going to go on a limb and assume already placed ones are the issue, rather than newly placed ones.

i would recommend going to the previous build with the extractors as they were, and dropping that file over top of the new ones. Then have your users remove all honey extractors. Then drop the new one back in. Should do the trick.

**Comment by samhaintm** [comment]
Thanks for the info. I'll give what you suggested a shot and see what happens. I just happened to start exploring bees about a day before the patch hit, and I figured it's just my luck lately. Thanks again.
