### ISSUE TITLE
[Feedback/Suggestion] Solar panel recipe changes

### ISSUE THREAD

**Issue by GregariousJB** [sayterdarkwynd/FrackinUniverse#1893]
Reference: https://github.com/sayterdarkwynd/FrackinUniverse/commit/2e80ff6859e26ca5a9455ee367a7f1fb82650692

Yikes this hurts. Some of us don't want to micromanage generator fuel along with everything else - cattle feed, crops, ship fuel, fertilizer, etc. Solar panels were a welcome release from that so we can get back to killing and exploring. 

If you're dead set on these changes, would you consider improving the existing solar panels a bit? Perhaps making a few new end-game solar panels that also work inside the ship?

**Comment by sayterdarkwynd** [comment]
Solar has been far, far too easy to produce since day 1. If you want pain-free, no-upkeep power, you pay at craft cost initially as a consequence.

The point is to encourage getting better power generators, not spamming solar. The cost increase isn't very substantial, it merely makes it so you can't just spam a thousand at tier 1.

I am not adding solar that works on the ship, since that encourages spamming the shitty power option, and there is no sun inside a starship anyhow. We also do not need end-game solar. By mid game you should be on Fission or Psionic generators, and by end-game, Quantum or Precursor generators, both of which are relatively pain-free since they can take common liquids as fuel.

**Comment by GregariousJB** [comment]
Oops, I meant _on_ the ship.

![yup](https://i.imgur.com/EcSkwD9.png)
