### ISSUE TITLE
Kicked back to Ship when moving towards a location

### ISSUE THREAD

**Issue by TheHeadmaster** [sayterdarkwynd/FrackinUniverse#2062]
FU Version: 5.6.361

I placed an Electronics Center (Tier 1) on a specific location on my map, and everything worked fine for several weeks. However, when i moved it and placed it in a new building i had recently made, I was leafing through the recipes and clicked one, and the server kicked me off to my ship (LAN Server) and ever since then if i move within 100 squares of it i get kicked off again. I can't even get close enough to it to see it on my screen before it will kick me off. Here's some logs to show what happens when I get kicked:

https://pastebin.com/dV6trsG3

If you have any insight as to what may be causing this It would be very appreciated.

**Comment by sayterdarkwynd** [comment]
the issue is whatever this shit is:

[21:27:35.035] [Error] WorldServerThread exception caught: (StarException) Maximum bound in randf must be >= minimum bound!


but I don't believe it has anything to do with FU. I've never even seen this error before. Might be a function from another of your mods.

Also, Optional Story is not compatible and should not be used.
