### ISSUE TITLE
"Monster Capturer" collection tab not displaying properly

### ISSUE THREAD

**Issue by SYK0503** [sayterdarkwynd/FrackinUniverse#2076]
Went through the FU collection tab cuz I was curious, all the other collection tabs seem to display correctly, with the exception for the "Monster Capturer" tab. Whenever I clicked into this tab, the collection window gets stuck, and other tabs won't display even if I click on it. Luckily, this doesn't seem to be a game breaking bug, and the collection window would work once I close and open it again. Screenshot down below:
![20200102140838_1](https://user-images.githubusercontent.com/59424780/71648520-14fb0580-2d6a-11ea-96e8-a76be59537b4.jpg)
Not sure what wrong here, my starbound logs down here:
[starbound.log](https://github.com/sayterdarkwynd/FrackinUniverse/files/4014730/starbound.log)

**Comment by sayterdarkwynd** [comment]
I'd wager its some sort of incompatability going on here. Virtually nobody has reported an issue here, and we havent touched that shit in ages. I can't be certain, though, since nothing looks like a red flag in your log.

id poke about at your installed mods and see what shakes out. If nothing seems to cause it, im not sure what is up and will investigate at that point...things dont just stop working for one user and nobody else :)

**Comment by SYK0503** [comment]
I look through my other mod and the only other mod that impact the custom collections UI was the Elithian Races Mod. Apparently, the problem was already there, but since it does not affect the gameplay and does not crash the game, it wasn't a significant issue.

It seems someone tried to fix this, so I will put down a link to the mod page just for reference:
https://steamcommunity.com/sharedfiles/filedetails/?id=1292295019

**Comment by sayterdarkwynd** [comment]
ive resolved the matter via our own scripts. seems that particular section had two entries pulled, but the numbers werent adjusted so the totals were off, mucking things up. Thanks.
