### ISSUE TITLE
Game crashed while "mining" near liquid Aether in ship, now crashes on load

### ISSUE THREAD

**Issue by flarn2006** [sayterdarkwynd/FrackinUniverse#2247]
I was outside of my ship, picking up some placed blocks; I think they were Jelly Blocks. There were also some adjacent Slime Blocks, both in the foreground and background layer, forming a small compartment which I had filled with liquid Aether. As soon as I picked up some of the blocks, the game instantly crashed to desktop. Now, every time I try to load that game file, it crashes. I've attached my shipworld file in case you can use it to figure out what happened.

[6938a2264d1eb8c90e94e795b718307a.shipworld.zip](https://github.com/sayterdarkwynd/FrackinUniverse/files/4767694/6938a2264d1eb8c90e94e795b718307a.shipworld.zip)

**Comment by sayterdarkwynd** [comment]
I can't. Head over to pastebin, and produce a pastebin of your log file. That, I can use.

**Comment by flarn2006** [comment]
https://pastebin.com/gwt2tvzz

Before you mention the Lua errors related to Improved Containers, that
isn't the cause of the problem, as it still happened even after
removing said mod.

**Comment by sayterdarkwynd** [comment]
Yea, and thats the problem with the improved containners spam.

The other issue is due to some tiles that were painted interacting with liquids and....ending up dyed invalidly. This is a pain in the ass to fix, but it certainly can be in some cases. For some reason the devs didn't include a failsafe state in case such things happened, which means in order to fix things the actual tiles config needs to be adjusted.

this requires knowing the exact tile, and seeing what its config file is, and then making the necessary adjustments.

**Comment by flarn2006** [comment]
Well if it helps, the only blocks that would have been around there are
jelly blocks and slime blocks. Maybe crystal blocks, but that's less likely.

What exactly are you saying is the issue with Improved Containers? Just
that it can mislead people into thinking it's the cause of a crash when it
isn't?

**Comment by sayterdarkwynd** [comment]
Improved Containers has some custom lua scripts. when you remove it, anything you had that used the script is going to constantly fire errors. That's what you have going on there. no big deal.

ill close the ticket now, as its unique to painting, and specifically only from liquid reactions. I'll note to investigate those three tile types though.
