### ISSUE TITLE
waterbarrel is potentially broken

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#242]
check it out. it could also be that the user has no clue what they are doing and ignored the tutorial text.

**Comment by renbear67** [comment]
That's related to the change someone suggested and made a while back, using wheat instead of "wheat seeds". Remember that? People are still trying to use wheat seeds rather than wheat. I tested it with wheat, and it works fine.

What I'd really like to see is a unification of wheat and wheat seeds, making one item act as both crafting ingredient and seed object. It should be possible, since wheat is no longer directly consumable. It might be beyond the scope of FU, though.

**Comment by sayterdarkwynd** [comment]
okay. so what i need to do is update the tutorial to tell them explicitlt to use wheat stalks. thanks
