### ISSUE TITLE
locked/destroyable doors

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#252]
can these be done? how complicated would it be>

**Comment by NotMrFlibble** [comment]
For locking in dungeons? Different than the default behaviour? Altering how a copy of /objects/wired/door/door.lua handles the input node will probably be enough.

Destroyable – set what is dropped when the object is removed to nothing, I think.

**Comment by renbear67** [comment]
Maybe he means, destroyed by damage?
Locking doors are already in Vanilla.

**Comment by sayterdarkwynd** [comment]
I mean lock/unlock with a specific object/item. A key, keycard, whatever. Right now it only goes via wiring to my knowledge.

Alternatively, combo locks would be an option.


and yes,doors  destroyed by damage as a potential thing too. Not EVERY door, just specifically flagged ones.

**Comment by IrisBlanche** [comment]
You could change the door behaviour by adding an extra interface with a item slot which triggers the door state. So keycard is in the slot: open, if not: close.
This would require the door and the keycard having an additional config parameter which contains the code.
If it should be placable by a player the door would need an extra behaviour for adding a code and creating a keycard for it (maybe using one of the crafting stations for this)

Just a few thoughts about it in theory. I can't say for sure if it would work because of the table restriction but it should work.

**Comment by IrisBlanche** [comment]
As an addition to my comment above: when adding an interface and allowing the door to be opened only if the card is present (or whatever lock mechanism is used) the input node must be changed (or removed) to prevent bypassing the mechanic.
