### ISSUE TITLE
Wired Industry's item routers – worth extending interoperability with these?

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#269]
not sure what you meant by this comment, but i posted here so you could remember about it. Care to elaborate?

**Comment by NotMrFlibble** [comment]
See [my wiredindustry branch](/NotMrFlibble/FrackinUniverse/tree/wiredindustry) for the hydroponics tray code.

**Comment by sayterdarkwynd** [comment]
and yes, worth extending for sure. Saves us needing to add such a feature to FU while maintaining compatibility with them

**Comment by NotMrFlibble** [comment]
It's those which have input item slots which need the modifications (and, arguably, not all should). Mostly, others can have item collectors placed beside them; one obvious exception is the honey jarrer since that doesn't have a specific input slot.

The extractors, xeno labs and smelters are obvious ones to do; the apiaries are obvious ones _not_ to do.
