### ISSUE TITLE
Several Monsters are not functioning properly

### ISSUE THREAD

**Issue by sayterdarkwynd** [sayterdarkwynd/FrackinUniverse#272]

**Comment by sayterdarkwynd** [comment]
toxicfly and other flys also. there may be more hidden around.

**Comment by Beanary** [comment]
I am having some issues as of lately (from a few versions ago) of this mod, some large creatures seem to have their AI broken or something, cause can't move. This includes The large version of the mechanical tarantula (regular works fine) the red poop monster, the giant scorpion, the giant jelly monster and the large brain robot (the one that used to be a boss in beta starbound) . The ones with ranged attack can aim and use it to attack, otherwise they don't interact at all, they can take damage though. 

Other large monsters work fine, this include like mountain trolls, the other types of large robots, the fish people, large dinosaurs and procedurally generated monsters.

**Comment by sayterdarkwynd** [comment]
a few left. closing this issue anyhow, since im not decided on what im doing with them yet.
