### ISSUE TITLE
Avali "small" teleporter needs too much space

### ISSUE THREAD

**Issue by Cyasi** [sayterdarkwynd/FrackinUniverse#3049]
Hello!

Short Story: 
Please add a real small teleporter variant for Avali like for Fenerox & co.

Long Story:
The racial changed teleporters (fu_byosteleporter in ship component racializer to avali ship spawn) needs way more space than the racial small teleporter spawns (Fenerox, Kirhos, Pharitu, Thelusian, Veluu'ish). 
It's pretty clear afterwards, the default shipspawn is tall but it is very confusing when changing it to the Avali ship spawn, which is small.

**Comment by Kherae** [comment]
every racialized ship teleporter uses the same default base object. the reason why we can't change this is because the placement collision is based on the actual base object, and cannot be overridden with parameters. @Hubnester  would have to put in some effort to rework the system to use the actual objects in place of texture overrides, and that'd likely be far beyond the scope of what is feasible.
