### ISSUE TITLE
Armour colorOptions tables + minor touchups

### ISSUE THREAD

**Issue by FullOfSpiders** [sayterdarkwynd/FrackinUniverse#467]
Many of the armour sets have small errors in their colorOptions tables that cause them to interact incorrectly with dyes. Usually they use an offset color value, or just eat the dye with no visible effect.

Most of them are an easy fix; I have some fixed up ones ready to go now even. Since it's grunty work, I'd love to fix them up myself so you all don't have to bother with it. I've even touched up a few, like adding a missing pixel or some shoes.

Now, I'm not much of an artist (or a coder, for that matter), but I don't think I can do much damage. Anything I put up can easily be changed, etc. Here's a sample of the devastation I've wrought so far.

![pantsf](https://cloud.githubusercontent.com/assets/23010197/21462209/23d954da-c90e-11e6-9a7b-58a85336e863.png)

Sweet shoes, no? Go ahead; stare into that abyss.

**Comment by sayterdarkwynd** [comment]
its mainly because the armors are, by and large, not dye compatible. without default palettes they will act funny regardless (only specific palette will be dyed, which needs to be custom-set if it is not the identical palette to vanilla)

youre more than welcome to do a pull request or whatnot, though
