### ISSUE TITLE
Master chest, item sorting, filtering and routing.

### ISSUE THREAD

**Issue by simdimdim** [sayterdarkwynd/FrackinUniverse#585]
I'm trying to build a comprehensive storage system where you tp to base, dump everything in 1 chest and routers lead it to different chests separated by type. Problems I've encountered so far include. liquids not being distinguished than other blocks on either "Type" or "Category", and routers instead of dropping items in the chests they get added to the routers filters. The idea was 'master chest'->bridge->router->router(s)->bridge(s)->chests(s) its somewhat working to the point of sucking out everything from the 1st chest, but after that its pretty much a mess.. tried repeaters without much (or any change). Also looking for a way for using 1 router for 2 chests (that possible?). Please advice. Thank you.

**Comment by blackfrogg** [comment]
This is not a official answer, but for now - When it comes to a master chest - You best bet is to use StarTech, a mod you prop already have installed since it is recommended for FU. StarTech provides a better filters and more advanced storage options. And it`s easier to set up, once you get the hang of it 

Here is a proper guide, part of which will be implemented into the FU guide for Networking (When i get the time, I have to flesh out the current one and adjust to the changes.) https://www.reddit.com/r/starbound/comments/537xox/startech_storage_mod/

When it comes to the FU Network, they work best in smaller setups as well as for making setups automatic. 

On your" 'master chest'->bridge->router->router(s)->bridge(s)->chests(s)" setup, I suspect that you cant really plug 2 routers in a row, in my mind because it should recognize the second one as a normal storage which would also explain why things ended up in your filter, but that might also be due to the newest changes that force you to wire after you have set your filter (Why ever that was needed)   - But I know you can run them parallel, by directly attaching all IDEs/routers to the master chest/Bridge. Then splitting up your stuff into chests wouldn't be a problem, I guess. Still, far more complicated, especially since you can also implement any container into Startech, just like you can do with FU's network.

**Comment by simdimdim** [comment]
I saw some youtube vids beforehand so I knew about the wire-afterwards thingy, and it works fine with just 1 chest, bridge, router, router, bridge, anotehr chest, but when there's a split/fork from 1 router to 2 the problem occurs. whole point was to have a resources lane/highway form which stuff could pull what they need/want something like the sushi bars with the transport belts, but right now it seems to be just a dream.
I saw the rec about star tech on the original page, but thought I'd like to avoid redundancy (since FU already had something like it), but it looks like there's some more functionality to be desired?)

I get the feeling if the problem of 1 router to multiple outputs could be solved it'd work just fine.
Either that or I'll have to come up with a logic network that controls the item network? is there tech similar to power/motion sensors for availability of items in a chest?

**Comment by blackfrogg** [comment]
As I said, I am not aware on how the code actually makes priorities when you chain them up, but it seems obvious to me that you can only have one output. The original version did not even support multiple inputs.

The CAT, as I call it, is decentralized, that`s exactly what makes it so special. There is no master. So if you attach 2 IDEs (routers) in a row you`ll eventually start a fight over who is master and slave, more so if you actually define the first one as master by forking. That`s not the idea of the network.

As mentioned the only way to do this is to set the IDEs in parallel. If you put a second chest after the master one, that would work, but you will never be able to actually fork of routers directly. They are not meant to be used in chains. No there is no such sensor.

Download StarTech. Actually read the tutorial I sent to you, If you want a master chest, StarTech will always be less complicated or more able, unless the complete interface of the IDE get`s reworked from scratch. StarTech is made for it, the FU network is not.

(If anyone of the devs reads this - That is why the mods need one guide that in-cooperates both mods)

**Comment by simdimdim** [comment]
@blackfrogg I checked out Startech if I could pair it with a repeater that has a on/off input it'd be perfect, that way I could have a server/drivebay for all the types (ores, liquids etc) and turn on only the connection to the place I want to store stuff at. (still not quite automated sorting but at least a bit less chest opening/closing)

Is there such a repeater somewhere?

**Comment by blackfrogg** [comment]
Read the tutorial dude
