### ISSUE TITLE
[Suggestion] Proposed prototype of organized crafting stations

### ISSUE THREAD

**Issue by rahlzel** [sayterdarkwynd/FrackinUniverse#78]
Continued from #61:

![Prototype](http://i.imgur.com/cjZ8nen.png)

**Comment by sayterdarkwynd** [comment]
decent ideas, but much of it breaks the concepts of some of the stations. The Clothing Fab is not changing. It exists specifically to provide non-metallic armors and such. 

The Matter Assembler creates the stations so that it is self-contained in FU, and because I don't want it gated behind a Tier 3 upgraded station. 

Still, some good concepts here and some I may just work in (categories, for instance, could stand some revision)

**Comment by rahlzel** [comment]
> It exists specifically to provide non-metallic armors and such.

Even though many of the craftable items in it require metal?

> The Matter Assembler creates the stations so that it is self-contained in FU, and because I don't want it gated behind a Tier 3 upgraded station.

I'm not sure I follow here. Do you mean it looks like I'm suggesting that you have the FU stations craftable within the default Architect Table? If so, that's not at all what I mean. It would be a whole separate station that works similarly to the Architect Table in that it houses all of the other crafting stations.

**Comment by rahlzel** [comment]
I just noticed two more sections of weapons and armor in the Nanofabricator, so that's three places to hunt down the same type of items - Clothing Fab, Armory, and Nanofabricator. 

I understand if the intention was to make this an "upgrader" type of station - I see the Quantum MK2 gear in here - but some of it isn't, like the Warrior gear (http://i.imgur.com/wB84f5j.png) or the Blister gear (http://i.imgur.com/HDoohka.png). For newbs like me, we just see three long lists of equipment to choose from in three different stations. 

Ok, I'm trying to refrain from walls of text, so I'm going to write up another prototype just for the Armory.

![armory](http://i.imgur.com/sAKOize.png)

**Comment by sayterdarkwynd** [comment]
What youve just done makes life a LOT more complicated for everyone.

now they not only have EXTRA stations, they also need to upgrade them. The end result being far more complicated than just using the initial 3 stations for armor, clothing and upgraded goods. 

Don't like it.

I also really, REALLY dislike the idea of a station to craft all the FU stations...since we already HAVE one called the matter assembler. No sir. Don't like that at all.



Again, appreciate the brainstorming...but I am not on-board with this one in its current state. Some decent concepts but nothing I would care to use at present.


Remember, just because *you* dont see the logic doesnt mean the logic is not there.

**Comment by rahlzel** [comment]
As much as I probably seem right now, I really don't want to be pushy about this. I'm just trying to help you understand why I'm making these suggestions.

By default, Starbound has one crafting station that is responsible for all weapons and armor, and it can be upgraded: http://starbounder.org/Anvil

By default, Terraria has one crafting station that is responsible for all weapons and armor, and it can be upgraded: http://terraria.gamepedia.com/Iron_Anvil

By default, Planet Centauri has one crafting station that is responsible for all weapons and armor, and it can be upgraded: http://planetcentauri.gamepedia.com/Anvils

By default, Crea has one crafting station that is responsible for all weapons and armor, but it doesn't get upgraded (yet): http://creawiki.net/w/Forge

This is why I've been recommending these changes. This isn't personal preference or because it seems more logical. It's because I'm regurgitating something that's objectively superior and has been for years.

That being said, YOU are completely in control here. If you want to have 100 weapons spread out over 100 different crafting stations, that's completely your choice. I'm just trying to point you to the path that should be seriously considered so that you can make a conscious, rational decision not to follow it. And if you so choose, then so be it.

Whatever happens, thank you again for this awesome mod, and I apologize if I've become "that guy in the issue tracker" as a result.

P.S. If you could kindly ask Renbear to check his email, I have a friendly tip in there for him about Rebasing instead of Merging to prevent merge commits from polluting your commit history.
