### ISSUE TITLE
Suggestion - Power Relay / Improve Power Logistics

### ISSUE THREAD

**Issue by BlackWyvern** [sayterdarkwynd/FrackinUniverse#88]
So perhaps it's me being new to the mod, but I've already run into some irks with the power system..

Running an atmospheric condenser and a powder sifter only consumes 7u that an 8u battery can supply, but due to even-share, the condenser offlines as soon as the sifter is connected. That just.. bothered me on a basic level, lol.

I can't pretend to know how complex Starbound's API is, but dividing the power that comes from a source to all machines connected to it evenly seems.. inefficient. Would it be possible to have machines draw what they need, instead of what the source decides to give them? Reverse the communications between the two, if that makes sense.

Power generation could be done much the same way. Currently, making a wild guess as to the inner workings, things work like this:
B1: '\o hai generator, i's machine'
Gen: 'o/ hai machine, haf 8 juice'

Then on subsequent connections

M1: '\o hai generator, i's machine'
M2: '\o hai generator, i's a machine 2, lolz!'
Gen: 'o/ hai machines, uhm, i alredy no a machine, so i guess all haf 2.67 juice now? soz'

Instead, I think optimally things should be:

B1: '\o hai generator, i's battery'
Gen 'o/ hai battery, i can send 8 juice, am sending machines 0 juice, and am sending batteries 0 juice. how many juice does need?'
B1: 'all juice pls'
Gen: 'ok can has all juice'

Then, on additional battery connections:

B2: '\o hai generator, i's battery'
Gen 'o/ hai battery, i can send 8 juice, am sending machines 0 juice, and am sending batteries 8 juice. how many juice does need?'
B2: 'all juice pls'
Gen: 'o. i has no juice left. Let me c if i can find juice...'
>.. i can send 8 juice
>.. i not no machine T.T, so still has 8 juice
>.. o! i no battery! he has 8 juice. now i no 2 battery, yey friends! means 4 juice each.

Gen: 'batteries! you can both has 4 juice! :D'

Conversely, on subsequent machine connections

M1: '\o hai generator, i's machine'
M2: '\o hai generator, i's a machine 2, lolz!'
Gen: ':o o/ hai machines, i can send 8 juice, am sending machines 0 juice, and am sending batteries 8 juice. how many juice does need?'
M1: 'o i need 2 juice pls'
M2: 'i need 5 juice D: i's fat'
Gen: 'o. i has no juice left. Let me c if i can find juice...'
>.. i can send 8 juice
>.. i not no machine b4 but now i no 2 machine, yey friends!
>.. machine 1 sez he want 2 juice, so has 6 juice now.
>.. machine 2 sez he want 5 juice, so has 1 juice now.
>.. i no batteries! they had 4 juice each. but now i has 1 juice.. D:!

Gen: 'ok. machine1 u has 2 juice, machine2 u has 5 juice. batteries i only has 1 juice, share, k?'

In the event of an over-load, one could either power the lowest consumption machines first, or power them in order of connection. This would send fractional power only to the last machine in that chain.

Batteries would function much the same as generators, they both output at specific rates, so the code could be the same in that regard.

------

Secondly, I'm a bit of a neat-freak when it comes to cabling. Having some kind of power relay that can freely transfer all the power going through it would greatly clean up birdnests. Could be built into something appealing like an overhead power conduit or something. It would count as a battery for priority, have no (or very limited) storage, but have no upper limit on the power transfer rate.

------

Anyways yeah. Feel free to call me dumb if this has all be suggested before, or if my implementation is dumb. I just figure, the worst you can say is no. Nothing changes if no one asks.

**Comment by renbear67** [comment]
No, I really appreciate the feedback, especially when it's so detailed. I haven't closely examined everything you posted yet, but wanted to acknowledge you ASAP. I'll get to it later tonight.

**Comment by Katorone** [comment]
Right now the power system seems a bit useless/unusable.  I'm playing around with it because of the cool factor, but so far the rewards from having the powered machines aren't enough of an incentive.

My suggestion for the power system would be (in addition to the one above)
- Rebalance machines so some require power to operate (eg the gene labs)
- Add more top tier alloys and ores into machines that require power to operate. This forces the use of these machines to create the top tier armours and weapons. (but this only works if the power system is fun and intuitive). This would make power a crafting ingredient.
- Let machines have an internal power buffer.  Or maybe an universal attachable battery (like the vanilla top tier anvils)
- Have a chip that can accumulate the power of the generators/batteries connected to it.  Attach 5x2u solar powers to such a chip to get a 1x10u connection.
- Allow solar panels to be upgraded/combined.  Perhaps up to 4 tiers, where each tier would require 2 panels of the tier below + some tiered material. These would double the output without growing much larger.
- Add a power requirement to quality of life improvements.

Ideas for quality of life improvements:
- automated hydroponics (robotics harvest & replant and stores produce in an internal cooled container)
- bigger fridges, maybe even automatically combine food items with the weighed average of their spoiling time.
- floodlights
- better turrets (range/damage)
- PVP roleplay elements: undestroyable hatches while powered, a generator like in the hylotl cities that protect a range from anyone breaking blocks. (Could even be a one-time huge investment to protect an entire planet, which can then be toggled on or off after a certain charge is reached.)
- Space mining at a huge power cost (like Minefactory Reloaded's Laser Drill).  Install this on a ship (not planet, it would melt your base), and it will mine (generate) materials that it would normally encounter on this planet.  Fun upgrades like ore scanners or focussing arrays could increase the productivity or efficiency at a higher energy cost.
- An equivalent exchange system, as a replacement for automated crafting. The raw minerals, nutrient paste etc, in addition with large amounts of energy, can be used to 'duplicate' items.
- jetpacks. (maybe the upgrade system can be used to recharge it with batteries by clicking on

**Comment by sayterdarkwynd** [comment]
some good ideas here. But I have 0 interest whatsoever in anything PVP. FU is not balanced in that way, and won't likely ever be.
